!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
batch_size: 1
commit_hash: 8447b88
data_steps: 128
dropout: 0.4
epochs: 250
last_activation: tanh
latent_dim: 64
learning_rate: 0.001
loss: mae
name: test-8447b88
phase: original
renorm: false
timestring: '2023-06-22T17:37:47'
