!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
batch_size: 8
data_steps: 64
epochs: 50
last_activation: relu
latent_dim: 128
loss: mae
name: test
phase: original
renorm: true
timestring: '2023-06-21T21:06:53'
