!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
batch_size: 1
commit_hash: 8447b88
data_steps: 64
dropout: 0.0
epochs: 250
last_activation: relu
latent_dim: 16
learning_rate: 0.01
loss: bce
name: test-8447b88
phase: original
renorm: false
timestring: '2023-06-22T18:22:25'
