!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
batch_size: 4
data_steps: 32
dropout: 0.25
epochs: 250
last_activation: relu
latent_dim: 512
learning_rate: 0.0001
loss: bce
name: test
phase: original
renorm: false
timestring: '2023-06-21T22:17:46'
