!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
batch_size: 8
commit_hash: '4980625'
data_steps: 8
decay_factor: 3.0
dropout: 0.0
epochs: 250
last_activation: tanh
latent_dim: 8
learning_rate: 0.02
loss: bce
name: test-4980625
phase: original
renorm: false
shuffle_data: true
timestring: '2023-06-23T14:30:56'
