!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
batch_size: 2
commit_hash: 31d7553
data_steps: 32
dropout: 0.0
epochs: 250
last_activation: relu
latent_dim: 256
learning_rate: 0.01
loss: bce
name: test-31d7553
phase: original
renorm: false
timestring: '2023-06-22T21:04:14'
