!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
batch_size: 8
data_steps: 16
dropout: 0.3
epochs: 50
last_activation: relu
latent_dim: 512
loss: bce
name: test
phase: original
renorm: false
timestring: '2023-06-21T21:34:51'
