!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
batch_size: 8
commit_hash: d6c7acf
data_steps: 8
decay_factor: 3.0
dropout: 0.0
epochs: 250
last_activation: tanh
latent_dim: 256
learning_rate: 0.02
loss: mae
name: test-d6c7acf
phase: original
renorm: false
timestring: '2023-06-23T10:29:13'
