!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
epochs: 50
last_activation: relu
latent_dim: 128
loss: mae
name: normalized_latent_256
phase: original
renorm: true
timestring: '2023-06-21T20:40:58'
