!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
epochs: 50
last_activation: relu
latent_dim: 1024
loss: l2norm
name: test
phase: original
renorm: true
timestring: '2023-06-21T20:59:29'
