!!python/object:printer_anomaly_detection.training.audio.AudioTrainingConfig
batch_size: 1
data_steps: 128
dropout: 0.25
epochs: 250
last_activation: relu
latent_dim: 32
learning_rate: 0.0001
loss: mae
name: test
phase: original
renorm: false
timestring: '2023-06-22T13:58:25'
